# here are some useful scripts especially written for this project 
# I just list them here
# ---
#   |
#   |--- __init__.py: some descriptions about this directory
#   |--- JSON_process.py: process the json file generated by web-frontend and transform its file format
#   |                     to .KINGHQ
#   |--- Draw_figures.py: users can specify the csv file in $KINGHQ/log/ that will be the 
#                         data source for drawing
#   |--- to be continued